[[plugins]]
repo = 'Shougo/neomru.vim'
on_path = '.*'
hook_add = '''
let g:neomru#file_mru_limit = 10000
'''

[[plugins]]
repo = 'Shougo/denite.nvim'
depends = ['neomru.vim', 'coc-denite']
on_cmd = 'Denite'
hook_post_source = '''
" call denite#custom#var('file_rec', 'command',
      " \ ['rg', '--files', '--glob', '!.git'])
      "
call denite#custom#var('file/rec', 'command',
      \ ['fd', '--follow', '--hidden', '--exclude', '.git', '--type', 'f', ''])
call denite#custom#alias('source', 'file/rec/git', 'file/rec')
call denite#custom#var('file/rec/git', 'command',
      \ ['git', 'ls-files', '-co', '--exclude-standard'])

call denite#custom#var('grep', 'command', ['rg'])
call denite#custom#var('grep', 'default_opts',
      \ ['--vimgrep', '--no-heading'])
call denite#custom#var('grep', 'recursive_opts', [])
call denite#custom#var('grep', 'pattern_opt', ['--regexp'])
call denite#custom#var('grep', 'separator', ['--'])
call denite#custom#var('grep', 'final_opts', [])

call denite#custom#map('insert', '<C-g>', '<denite:enter_mode:normal>', 'noremap')
call denite#custom#map('insert', '<C-n>', '<denite:move_to_next_line>')
call denite#custom#map('insert', '<C-p>', '<denite:move_to_previous_line>')

" display configurations
let s:denite_win_width_percent = 0.85
let s:denite_win_height_percent = 0.7

call denite#custom#option('default', {
      \ 'split': 'floating',
      \ 'winwidth': float2nr(&columns * s:denite_win_width_percent),
      \ 'wincol': float2nr((&columns - (&columns * s:denite_win_width_percent)) / 2),
      \ 'winheight': float2nr(&lines * s:denite_win_height_percent),
      \ 'winrow': float2nr((&lines - (&lines * s:denite_win_height_percent)) / 2),
      \ 'highlight_filter_background': 'DeniteFilter',
      \ 'prompt': '⫸ ',
      \ 'start_filter': v:true,
      \ })

autocmd FileType denite set winblend=10
autocmd FileType denite-filter set winblend=10
'''
hook_add = '''
autocmd FileType denite call s:denite_my_settings()
function! s:denite_my_settings() abort
  nnoremap <silent><buffer><expr> i
        \ denite#do_map('open_filter_buffer')
  nnoremap <silent><buffer><expr> q
        \ denite#do_map('quit')
  nnoremap <silent><buffer><expr> <CR>
        \ denite#do_map('do_action')
  nnoremap <silent><buffer><expr> p
        \ denite#do_map('do_action', 'preview')
endfunction

nnoremap [denite] <Nop>
nmap <Space>f [denite]
"nnoremap [denite]b :<C-u>Denite buffer<CR>
nnoremap [denite]b :<C-u>Denite buffer file_mru<CR>
nnoremap [denite]l :<C-u>Denite line<CR>
nnoremap [denite]t :<C-u>Denite filetype<CR>
nnoremap [denite]f :<C-u>DeniteProjectDir file/rec<CR>
nnoremap [denite]F :<C-u>Denite file/rec<CR>
nnoremap [denite]G :<C-u>Denite grep<CR>
nnoremap [denite]g :<C-u>DeniteCursorWord grep<CR>
nnoremap [denite]r :<C-u>Denite-resume<CR>
nnoremap [denite]c :<C-u>Denite command<CR>
nnoremap [denite]h :<C-u>Denite help<CR>
nnoremap [denite]cc :<C-u>Denite coc-command<CR>
nnoremap [denite]cd :<C-u>Denite coc-diagnostic<CR>
nnoremap [denite]cs :<C-u>Denite coc-symbols<CR>
'''

# [[plugins]]
# repo = 'Shougo/deoplete.nvim'
# on_event = 'InsertEnter'
# depends = ['deoplete-lsp', 'deoplete-tabnine']
# hook_source = '''
  # let g:deoplete#enable_at_startup = 1
  # let g:deoplete#tag#cache_limit_size = 10000000
  # inoremap <expr><TAB>  pumvisible() ? "\<C-n>" : "\<TAB>"
  # inoremap <expr><S-TAB>  pumvisible() ? "\<C-p>" : "\<S-TAB>"
  # inoremap <expr><CR>  pumvisible() ? deoplete#close_popup() : "<CR>"
# '''

# [[plugins]]
# repo = 'tbodt/deoplete-tabnine'
# build = './install.sh'

# [[plugins]]
# repo = 'Shougo/deoplete-lsp'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/neosnippet'
on_event = 'InsertEnter'
on_ft = ['snippet']
depends = ['neosnippet-snippets']
hook_source = '''
imap <C-k> <Plug>(neosnippet_expand_or_jump)
smap <C-k> <Plug>(neosnippet_expand_or_jump)
xmap <C-k> <Plug>(neosnippet_expand_target)
if has('conceal')
  set conceallevel=2 concealcursor=niv
endif
'''

[[plugins]]
repo = 'previm/previm'
on_ft = ['markdown']
hook_source = '''
let g:previm_open_cmd = $BROWSER
nnoremap <silent> <Space>mp :<C-u>PrevimOpen<CR>
'''

