[[plugins]]
repo = 'KeitaNakamura/neodark.vim'
hook_add = '''
let g:neodark#use_256color = 1
function! EnableNeoDark()
  colorscheme neodark
  hi Normal guifg=#bcbcbc guibg=#242424
  hi IncSearch gui=bold,italic guifg=#ffcc00 guibg=#242424
  hi Search gui=bold,italic guifg=#ffa64d guibg=#242424
  hi LineNr guifg=#474646 guibg=#202020
  hi CursorLine guibg=#343434
  hi CursorLineNr guifg=#669999 guibg=#343434
  hi NormalFloat guibg=#1a1a1a
endfunction
autocmd VimEnter * nested call EnableNeoDark()
'''

[[plugins]]
repo = 'tyrannicaltoucan/vim-quantum'
hook_add = '''
let g:quantum_black=1
let g:quantum_italic=1
function! EnableQuantum()
  colorscheme quantum
  hi IncSearch gui=bold,italic guifg=#ffcc00 guibg=#242424
  hi Search gui=bold,italic guifg=#ffa64d guibg=#242424
  hi LineNr guifg=#474646 guibg=#202020
  hi CursorLine guibg=#343434
  hi CursorLineNr guifg=#669999 guibg=#343434
  hi MatchParen gui=bold guifg=#1affb2 guibg=#242424
  hi NormalFloat guibg=#1a1a1a
endfunction
" autocmd VimEnter * nested call EnableQuantum()
'''

[[plugins]]
repo = 'morhetz/gruvbox'
hook_add = '''
" colorscheme gruvbox
'''
hook_add = '''
function! EnableGruvbox()
  colorscheme gruvbox
  " hi IncSearch gui=bold,italic guifg=#ffcc00 guibg=#242424
endfunction
" autocmd VimEnter * nested call EnableGruvbox()
'''

[[plugins]]
repo = 'arcticicestudio/nord-vim'
hook_add = '''
function! EnableNord()
  colorscheme nord
  hi IncSearch gui=bold,italic guifg=#ffcc00 guibg=#242424
endfunction
" autocmd VimEnter * nested call EnableNord()
'''

[[plugins]]
repo = 'sainnhe/everforest'
hook_add = '''
function! EnableEverforest()
  colorscheme everforest
  hi Normal guifg=#bcbcbc guibg=#242424
endfunction
" autocmd VimEnter * nested call EnableEverforest()
'''

[[plugins]]
repo = 'doums/darcula'
hook_add = '''
function! EnableDarcula()
  colorscheme darcula
endfunction
" autocmd VimEnter * nested call EnableDarcula()
'''
