[[plugins]]
repo = 'tyru/caw.vim'

[[plugins]]
repo = 'machakann/vim-sandwich'
hook_add = '''
" dとrは自動検出なので、マニュアルでやるときは、
" ex) + から / に変換
" sr+/ と入力
" みたいな感じ
nmap <Space>s [sandwich]
nmap [sandwich]a <Plug>(operator-sandwich-add)
nmap [sandwich]d <Plug>(operator-sandwich-delete)
nmap [sandwich]r <Plug>(operator-sandwich-replace)
vmap sa <Plug>(operator-sandwich-add)
vmap sd <Plug>(operator-sandwich-delete)
vmap sr <Plug>(operator-sandwich-replace)
'''

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'elixir-editors/vim-elixir'
on_ft = 'ex,eex,exs'

[[plugins]]
repo = 'elzr/vim-json'
hook_add = '''
let g:vim_json_syntax_conceal = 0
'''

[[plugins]]
repo = 'aklt/plantuml-syntax'
on_ft = 'pu,uml,puml,plantuml'
hook_add = '''
au FileType plantuml command! OpenUml :!chromium %
'''

[[plugins]]
repo = 'leafgarland/typescript-vim'

[[plugins]]
repo = 'peitalin/vim-jsx-typescript'

[[plugins]]
repo = 'posva/vim-vue'
hook_add = '''
autocmd FileType vue syntax sync fromstart
'''

[[plugins]]
repo = 'prettier/vim-prettier'
build = 'npm install'
on_ft = ['javascript', 'typescript', 'vue', 'css', 'scss', 'json', 'markdown']
hook_add = '''
let g:prettier#autoformat = 0
autocmd BufWritePre *.js,*.ts,*.vue,*.css,*.scss,*.json PrettierAsync
'''

[[plugins]]
repo = 'amadeus/vim-mjml'
on_ft = ['mjml']
