[[plugins]]
repo = 'w0rp/ale'
hook_add = '''
let g:ale_linters = {
  \  'javascript': ['eslint'],
  \  'python': ['flake8'],
  \  'ruby': ['rubocop'],
  \}
let g:ale_sign_error = '⨉'
let g:ale_sign_warning = '⚠ '
let g:ale_statusline_format = ['⨉ %d', '⚠ %d', '⬥ ok']
let g:ale_echo_msg_error_str='E'
let g:ale_echo_msg_warning_str='W'
let g:ale_echo_msg_format='[%linter%] %s [%severity%]'
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 0
" let g:ale_set_loclist = 0
" let g:ale_set_quickfix = 1
" let g:ale_open_list = 1
" let g:ale_keep_list_window_open = 0
nmap <silent> <Space>sp <Plug>(ale_previous_wrap)
nmap <silent> <Space>sn <Plug>(ale_next_wrap)
'''

[[plugins]] # toml syntax
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'elixir-editors/vim-elixir'
on_ft = 'ex,eex,exs'

[[plugins]]
repo = 'elzr/vim-json'
hook_add = '''
let g:vim_json_syntax_conceal = 0
'''

[[plugins]]
repo = 'aklt/plantuml-syntax'
on_ft = 'pu,uml,puml,plantuml'
hook_add = '''
au FileType plantuml command! OpenUml :!chromium %
'''

