[[plugins]]
repo = 'Shougo/neomru.vim'
on_path = '.*'
hook_add = '''
let g:neomru#file_mru_limit = 10000
'''

[[plugins]]
repo = 'Shougo/denite.nvim'
depends = ['neomru.vim']
on_cmd = 'Denite'
hook_post_source = '''
call denite#custom#var('file_rec', 'command',
      \ ['rg', '--files', '--glob', '!.git'])
call denite#custom#var('grep', 'command', ['rg'])
call denite#custom#var('grep', 'recursive_opts', [])
call denite#custom#var('grep', 'final_opts', [])
call denite#custom#var('grep', 'separator', ['--'])
call denite#custom#var('grep', 'default_opts',
      \ ['--vimgrep', '--no-heading'])
call denite#custom#map('insert', '<C-g>', '<denite:enter_mode:normal>', 'noremap')
call denite#custom#map('insert', '<C-n>', '<denite:move_to_next_line>')
call denite#custom#map('insert', '<C-p>', '<denite:move_to_previous_line>')
'''

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_source = '''
  let g:deoplete#enable_at_startup = 1
  inoremap <expr><tab> pumvisible() ? "\<C-n>" :
        \ neosnippet#expandable_or_jumpable() ?
        \    "\<Plug>(neosnippet_expand_or_jump)" : "\<tab>"
'''
on_i = 1

[[plugins]]
repo = 'Shougo/neosnippet'
hook_source = '''
  imap <C-k> <Plug>(neosnippet_expand_or_jump)
  smap <C-k> <Plug>(neosnippet_expand_or_jump)
  xmap <C-k> <Plug>(neosnippet_expand_target)
  if has('conceal')
    set conceallevel=2 concealcursor=niv
  endif
'''
on_i  = 1
on_ft = ['snippet']
depends = ['neosnippet-snippets']

[[plugins]]
repo = 'osyo-manga/vim-monster'
on_ft = ['ruby', 'haml']
hook_source = '''
let g:monster#completion#rcodetools#backend = "async_rct_complete"
let g:deoplete#sources#omni#input_patterns = {
\   "ruby" : '[^. *\t]\.\w*\|\h\w*::',
\}
'''

[[plugins]]
repo = 'tpope/vim-rails'
on_ft = ['ruby', 'haml']
hook_source = '''
nnoremap <silent> <Space>ra :<C-u>A<CR>
nnoremap <silent> <Space>rr :<C-u>R<CR>
'''

[[plugins]]
repo = '5t111111/denite-rails'
on_ft = ['ruby', 'haml']
hook_source = '''
nnoremap [rails] <Nop>
nmap     <Space>r [rails]
" nnoremap <silent> [rails]r :<C-u>Denite<Space>rails:dwim<Return>
nnoremap <silent> [rails]m :<C-u>Denite<Space>rails:model<Return>
nnoremap <silent> [rails]c :<C-u>Denite<Space>rails:controller<Return>
nnoremap <silent> [rails]v :<C-u>Denite<Space>rails:view<Return>
nnoremap <silent> [rails]h :<C-u>Denite<Space>rails:helper<Return>
" nnoremap <silent> [rails]s :<C-u>Denite<Space>rails:test<Return>
'''

[[plugins]]
repo = 'osyo-manga/vim-watchdogs'
depends = ['vim-quickrun', 'vimproc', 'shabadou.vim', 'vim-hier', 'quickfixstatus']
on_event = ['BufWritePost']
on_ft = ['vim', 'python', 'ruby', 'elixir', 'zsh']
hook_source = '''
let g:quickrun_config = get(g:, 'quickrun_config', {})
let g:watchdogs_check_BufWritePost_enable = 1
let g:quickrun_config = {
\   "ruby/watchdogs_checker" : {
\       "type" : "watchdogs_checker/rubocop"
\   }
\}
'''

