[[plugins]]
repo = 'KeitaNakamura/neodark.vim'
hook_add = '''
let g:neodark#use_256color = 1
function! EnableNeoDark()
  colorscheme neodark
  hi Normal guifg=#bcbcbc guibg=#242424
  hi IncSearch gui=bold,italic guifg=#ffcc00 guibg=#242424
  hi Search gui=bold,italic guifg=#ffa64d guibg=#242424
  hi LineNr guifg=#474646 guibg=#202020
  hi CursorLine guibg=#343434
  hi CursorLineNr guifg=#669999 guibg=#343434
  hi NormalFloat guibg=#1a1a1a
endfunction
" autocmd VimEnter * nested call EnableNeoDark()
'''

[[plugins]]
repo = 'morhetz/gruvbox'
hook_add = '''
" colorscheme gruvbox
'''
hook_add = '''
function! EnableGruvbox()
  colorscheme gruvbox
  " hi IncSearch gui=bold,italic guifg=#ffcc00 guibg=#242424
endfunction
" autocmd VimEnter * nested call EnableGruvbox()
'''

[[plugins]]
repo = 'arcticicestudio/nord-vim'
hook_add = '''
function! EnableNord()
  colorscheme nord
  hi IncSearch gui=bold,italic guifg=#ffcc00 guibg=#242424
endfunction
" autocmd VimEnter * nested call EnableNord()
'''

[[plugins]]
repo = 'sainnhe/everforest'
hook_add = '''
function! EnableEverforest()
  colorscheme everforest
  hi Normal guifg=#bcbcbc guibg=#242424
endfunction
" autocmd VimEnter * nested call EnableEverforest()
'''

[[plugins]]
repo = 'EdenEast/nightfox.nvim'
hook_add = '''
lua << EOF
local palettes = {
  nightfox = {
  },
  duskfox = {
  },
  nordfox = {
    bg1 = '#1e2430'
  },
  terafox = {
  },
  carbonfox = {
  },
}
require('nightfox').setup({
  options = {
    styles = {
      comments = "italic",
      keywords = "bold",
      types = "italic,bold",
    }
  },
  palettes = palettes
})
vim.cmd("colorscheme nordfox")
EOF
'''

[[plugins]]
repo = 'rebelot/kanagawa.nvim'
hook_add = '''
lua << EOF
require('kanagawa').setup({
  undercurl = true,           -- enable undercurls
  commentStyle = { italic = true },
  functionStyle = {},
  keywordStyle = { italic = true},
  statementStyle = { bold = true },
  typeStyle = {},
  variablebuiltinStyle = { italic = true},
  specialReturn = true,       -- special highlight for the return keyword
  specialException = true,    -- special highlight for exception handling keywords
  transparent = false,        -- do not set background color
  dimInactive = false,        -- dim inactive window `:h hl-NormalNC`
  globalStatus = false,       -- adjust window separators highlight for laststatus=3
  terminalColors = true,      -- define vim.g.terminal_color_{0,17}
  colors = {
    bg = "#272727",
  },
  overrides = {},
  theme = "dark",             -- Load "default" theme or the experimental "light" theme
})
-- vim.cmd("colorscheme kanagawa")
EOF
'''
