[[plugins]]
repo = 'folke/which-key.nvim'
hook_add = '''
lua << EOF
  require("which-key").setup{
  }

  require("which-key").register({
    w = {
      name = "+window",
      h = { "<C-w>h", "move left" },
      j = { "<C-w>j", "move down" },
      k = { "<C-w>k", "move up" },
      l = { "<C-w>l", "move right" },
      s = { ":<C-u>split<CR>", "split" },
      v = { ":<C-u>vsplit<CR>", "vsplit" },
      d = { ":<C-u>q<CR>", "delete" },
      w = { ":MaximizerToggle<CR>", "toggle miximize" },
      [0] = { "<C-w>=", "size reset" },
    }
  }, { prefix = "<space>", noremap = true, mode = "n" })

  require("which-key").register({
    b = {
      name = "+buffer",
      n = { ":<C-u>bnext<CR>", "next" },
      p = { ":<C-u>bprevious<CR>", "previous" },
      d = { ":<C-u>bdelete<CR>", "delete" },
      a = { ":<C-u>enew<CR>", "add" },
      w = { ":<C-u>w<CR>", "write" },
    }
  }, { prefix = "<space>", noremap = true, mode = "n" })

  require("which-key").register({
    q = {
      name = "+quit",
      q = { ":<C-u>q<CR>", "quit" },
      w = { ":<C-u>wq<CR>", "with write" },
      a = { ":<C-u>qa<CR>", "quit all" },
      f = { ":<C-u>qa!<CR>", "force quit" },
    }
  }, { prefix = "<space>", noremap = true, mode = "n" })

  -- emacs keys
  require("which-key").register({
    ["<c-b>"] = { "<Left>", "left" },
    ["<c-f>"] = { "<Right>", "right" },
    ["<c-a>"] = { "<C-O>^", "home" },
    ["<c-e>"] = { "<End>", "end" },
    ["<c-h>"] = { "<C-g>u<C-h>", "delete forward" },
    ["<c-d>"] = { "<C-g>u<Del>", "delete" },
  }, { mode = "i" })


  require("which-key").register({
    ["<esc><esc>"] = { ":nohlsearch<CR>", "clear highlight" }
  }, { mode = "n" })
EOF
'''
