[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
hook_post_update = '''
  if dein#util#_is_windows()
    let cmd = 'tools\\update-dll-mingw'
  elseif dein#util#_is_cygwin()
    let cmd = 'make -f make_cygwin.mak'
  elseif executable('gmake')
    let cmd = 'gmake'
  else
    let cmd = 'make'
  endif
  let g:dein#plugin.build = cmd
'''


[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'scrooloose/syntastic.git'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'Shougo/neosnippet'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'


[[plugins]]
repo = 'bling/vim-bufferline'

[[plugins]]
repo = 'thinca/vim-localrc'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'moznion/github-commit-comment.vim'

[[plugins]]
repo = 'osyo-manga/vim-over'

[[plugins]]
repo = 'rhysd/clever-f.vim'

[[plugins]]
repo = 'majutsushi/tagbar'

[[plugins]]
repo = 'koron/codic-vim'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'thinca/vim-visualstar'

[[plugins]]
repo = 'thinca/vim-ref'

[[plugins]]
repo = 'scrooloose/nerdcommenter'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'haya14busa/incsearch.vim'

[[plugins]]
repo = 'haya14busa/incsearch-fuzzy.vim'

[[plugins]]
repo = 'haya14busa/incsearch-easymotion.vim'

[[plugins]]
repo = 'tpope/vim-endwise'

[[plugins]]
repo = 'tpope/vim-abolish'


[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'kannokanno/previm'

[[plugins]]
repo = 'mattn/vim-maketable'

[[plugins]]
repo = 'tpope/vim-rails'
[[plugins]]
repo = 'slim-template/vim-slim'
[[plugins]]
repo = 'elixir-lang/vim-elixir'
[[plugins]]
repo = 'kchmck/vim-coffee-script'

[[plugins]]
repo = 'w0ng/vim-hybrid'
[[plugins]]
repo = 'vim-scripts/darkburn'
[[plugins]]
repo = 'nanotech/jellybeans.vim'
[[plugins]]
repo = 'jpo/vim-railscasts-theme'
[[plugins]]
repo = 'chriskempson/vim-tomorrow-theme'
[[plugins]]
repo = 'vim-scripts/twilight'
[[plugins]]
repo = 'vim-scripts/wombat256.vim'
